##**5.16 List 2 Dimensi**
List 2 dimensi adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matriks.

In [1]:
# Latihan list 2 dimensi (1)

print('List terakhir isi tanda koma')
# Mendeklarasikan variabel berupa list
matriks_10 = [
    [1,3,5,7],        # Baris ke 0 atau -4
    [2,4,6,8],        # Baris ke 1 atau -3
    [9,11,13,15],     # Baris ke 2 atau -2
    [10,12,14,16],    # Baris ke 3 atau -1
]
print(matriks_10)

print('\nList terakhir tanpa tanda koma')     # \n berfungsi untuk membuat paragraf baru
matriks_10 = [
    [1,3,5,7],
    [2,4,6,8],
    [9,11,13,15],
    [10,12,14,16]
]
print(matriks_10)

# Ingat!!! Setiap akhir list ditambahkan tanda koma, kalau tidak isi akan error
# Tapi, list paling terakhir boleh tidak isi tanda koma, boleh juga isi.
# Bisa dilihat pada output hasilnya sama baik yang menggunakan tanda koma atau tidak pada list terakhir

List terakhir isi tanda koma
[[1, 3, 5, 7], [2, 4, 6, 8], [9, 11, 13, 15], [10, 12, 14, 16]]

List terakhir tanpa tanda koma
[[1, 3, 5, 7], [2, 4, 6, 8], [9, 11, 13, 15], [10, 12, 14, 16]]


In [2]:
# Latihan list  dimensi (2)

# Pada matriks, list pertama dari depan disebut baris ke 0, list kedua dari depan disebut baris 1,dst.
# Sedangkan list pertama dari belakang disebut baris ke -1, list kedua dari belakang disebut baris -2, dst.
# [1,3,5,7] adalah baris ke 0 atau -4
# [2,4,6,8] adalah baris ke 1 atau -3
# [9,11,13,15] adalah baris ke 2 atau -2
# [10,12,14,16] adalah baris ke 3 atau -1

print(matriks_10 [2])
# Ini artinya memanggil list matriks_10  pada baris ke 2

print(matriks_10 [0])
# Ini artinya memanggil list matriks_10 baris ke 0

print(matriks_10[-1])
# Ini artinya memanggil list baris -1 (list pertama dari belakang)

[9, 11, 13, 15]
[1, 3, 5, 7]
[10, 12, 14, 16]


In [3]:
# Latihan list 2 dimensi (3)

# Kolom pada matriks sama seperti baris pada matriks
# Kolom pada matriks dimulai dari 0 jika dari list terdepan
# Sedangkan jika dari list terbelakang, kolom dimulai dari -1
# 1,2,9,10 adalah kolom ke 0 atau -4
# 3,4,11,12 adalah kolom ke 1 atau -3
# 5,6,13,14 adalah kolom ke 2 atau -2
# 7,8,15,16 adalah kolom ke 3 atau -1

print(matriks_10[0][2])
# Ini artinya memanggil data pada matriks_10 baris ke 0 dan kolom ke 2
# [ ] pertama artinya posisi baris
# [ ] kedua artinya posisi kolom

print(matriks_10[-1][0])
# Ini artinya memanggil data pada matriks_10 baris -1 dan kolom ke 0

print(matriks_10[-1][-3])
# Ini artinya memanggil data pada matriks_10 baris -1 dan kolom -3

5
10
12


In [4]:
#Latihan list 2 dimensi (4) 
# Mengganti data pada list

matriks_10[0][3] = 20
# Disini artinya mengganti data list baris ke 0 dan kolom ke 3 yang seharusnya adalah 5 menjadi 20
print(matriks_10[0][3])

matriks_10[-1][2] = 6
# Disini artinya mengganti data list baris -1 dan kolom ke 2 yang seharusnya adalah 10 menjadi 6
print(matriks_10[-1][2])

20
6


In [5]:
# Latihan list 2 dimensi (5)

# Disini saya memanggil semua data pada matriks_10
matriks_10
# Output yang dihasilkan berbeda dengan pada latihan list 2 dimensi (1)
# Hal ini karena, sebelumnya saya sudah mengganti beberapa data list dengan data lain
# Sehingga, data tersebut menggantikan posisi data sebelumnya

[[1, 3, 5, 20], [2, 4, 6, 8], [9, 11, 13, 15], [10, 12, 6, 16]]

##**5.17 Tuples**
Tuples mirip seperti list, tetapi tuples tidak dapat dirubah isinya.

In [6]:
# Latihan tuples (1)

# Mendeklarasikan variabel
tuples_10 = (3,4,5,6,7,8,9,4,6,8)
# Berbeda dengan list, tuples menggunakan tanda kurung biasa
print(tuples_10)

(3, 4, 5, 6, 7, 8, 9, 4, 6, 8)


In [7]:
# Latihan tuples (2)

# Fungs append, remove, insert, dll tidak bisa digunakan karena data pada tuples tidak dapat dirubah
tuples_10.append(10)
tuples_10.remove(5)
# Perintah di atas akan error karena pada tuples tidak bisa menggunakan fungsi 'append', 'remove', dll seperti pada list

AttributeError: ignored

In [8]:
# Latihan tuples (3)

# Pada tuples hanya bisa menggunakan fungsi 'count' dan 'index'
# count berfungsi untuk menghitung berapa banyak data muncul pada suatu variabel.
print(tuples_10.count(4))
print(tuples_10.count(5))

# index berfungsi untuk mengetahui posisi data yang ingin kita ketahui pada suatu variabel
# Sama seperti sebelumnya index dimulai dari 0
print(tuples_10.index(9))

# Mencari posisi data menggunakan batas 
print(tuples_10[0:5])
# Ingat!! Batas akhir tidak ikut dicetak

2
1
6
(3, 4, 5, 6, 7)


In [9]:
# Latihan tuples (4)

# Mencetak semua data pada tuples_10 satu per satu
for data in tuples_10:
  print(data)

3
4
5
6
7
8
9
4
6
8


##**5.18 Dictionaries**
Dictionaries digunakan jika datanya terkait satu sama lain. Dictionary nama lainnya adalah associative array.

In [10]:
# Latihan dictionaries (1)

# Untuk mengakses data pada dictionaries kita menggunakan indentifies disebut key
# Sehingga untuk mengakses data tidak menggunakan index seperti pada list

# Mendeklarasikan variabel
data_10 = {
    'nama' : 'Universitas Udayana',
    'fakultas' : '13 Fakultas',
    'Apakah kampus negeri?' : True
}
# Dictionaries menggunakan kurung kurawal "{ }"
# 'nama', 'fakultas', 'Apakah kampus negeri' adalah key
# 'Universitas Udaya', '13 Falkultas', dan True adalah value
# Pada value bisa dimasukkan data berupa apapun baik itu string, boolean, list, dll
# Antara key dan value dipisahkan oleh tanda titik dua ':'

print(data_10['nama'])
print(data_10['Fakultas'])      # Ini akan error karena key 'Fakultas' tidak ada pada variabel data_10

Universitas Udayana


KeyError: ignored

In [11]:
# Latihan dictionaries 2 
# Mencari panjang dictionaries
lendata_10 = len(data_10)
print(f'Panjang dictionaries adalah', lendata_10)

Panjang dictionaries adalah 3


In [12]:
# Latihan dictionaries 3
# Mengecek key ada atau tidak pada variabel

key = 'nama'
checkkey = key in data_10
print(f"Apakah {key} ada di data ?", checkkey)    # Menggunakan formatted string
# Outputnya akan True karena key 'nama' ada pada variabel data_10

key = 'umur'
checkkey = key in data_10
print(f"Apakah {key} ada di data ?", checkkey)
# Output akan False karena key 'umur' tidak ada pada variabel data_10

Apakah nama ada di data ? True
Apakah umur ada di data ? False


In [13]:
# Latihan dictionaries 4
# Memanggil value pada variabel menggunakan get
# Memanggil value pada dictionaries bisa tanpa menggunakan 'get'
# Namun, saat key ataupun value tidak ada pada variabel, program akan error.
# Untuk itu, digunakanlah 'get'

print('Ini tanpa menggunakan "get"')
print(data_10['fakultas'])
print('\nIni menggunakan "get"')
print(data_10.get('fakultas'))

print('\nBisa dilihat outputnya sama baik yang menggunakan get atau tidak')
print('Outputnya akan berbeda saat key atau value tidak ada pada variabel')
print('\nIni saat key ataupun value tidak ada pada variabel')
print(data_10.get('tahun'))                                 # Menggunakan 'get' maka outputnya akan 'none'
print(data_10.get('tahun', 'Key "tahun" tidak ditemukan'))  # Bahkan saat menggunakan get, kita bisa mengganti output 'none'
print(data_10['tahun'])                                     # Tanpa menggunakan 'get', outputnya akan error

Ini tanpa menggunakan "get"
13 Fakultas

Ini menggunakan "get"
13 Fakultas

Bisa dilihat outputnya sama baik yang menggunakan get atau tidak
Outputnya akan berbeda saat key atau value tidak ada pada variabel

Ini saat key ataupun value tidak ada pada variabel
None
Key "tahun" tidak ditemukan


KeyError: ignored

In [14]:
# Latihan dictionaries 5
# Memperbarui atau menambahkan dictionaries menggunakan 'update'
print('Dictionaries yang sudah ditambahkan data baru')
data_10.update({'letak':'Provinsi Bali'})
print(data_10)
# Data pada dictionaries akan otomatis diperbarui atau ditambahkan dengan data yang diinginkan

Dictionaries yang sudah ditambahkan data baru
{'nama': 'Universitas Udayana', 'fakultas': '13 Fakultas', 'Apakah kampus negeri?': True, 'letak': 'Provinsi Bali'}


In [15]:
# Menghapus data pada dictionaries menggunakan 'del'
print('Dictionaries yang dihapus salah satu datanya')
del data_10['fakultas']
print(data_10)

Dictionaries yang dihapus salah satu datanya
{'nama': 'Universitas Udayana', 'Apakah kampus negeri?': True, 'letak': 'Provinsi Bali'}


In [16]:
# Latihan dictionaries 6 membuat jadwal kuliah
# Mencoba membuat dictionary dalam dictionary

# Mendeklarasikan beberapa dictionary
matkul1_10 = {
    'nama': 'Algoritma dan Struktur Data',
    'sks' : 3,
    'hari' : 'Senin',
    'jam' : '08.30 - 11.10'
}

matkul2_10 = {
    'nama': 'Struktur Aljabar',
    'sks' : 2,
    'hari' : 'Senin',
    'jam' : '11.10 - 13.00'
}

matkul3_10 = {
    'nama': 'Kalkulus II',
    'sks' : 3,
    'hari' : 'Selasa',
    'jam' : '08.30 - 11.10'
}

matkul4_10 = {
    'nama': 'Statistika Dasar',
    'sks' : 3,
    'hari' : 'Selasa',
    'jam' : '11.10 - 13.50'
}

datamatkul_10 = {
    'mat1' : matkul1_10,
    'mat2' : matkul2_10,
    'mat3' : matkul3_10,
    'mat4' : matkul4_10
 }

print('Berikut adalah jadwal kuliah anda selama semester genap\n')
print(f"{'KODE':^5} {'NAMA':^30} {'SKS':^3} {'HARI':^7} {'JAM':^13}")
# tanda '^' berfungsi agar tulisan dicetak ditengah-tengah (center)
print('='*65) 

# Melakukan for loop pada datamatkul_10
for matkul in datamatkul_10:
  key = matkul

  nama = datamatkul_10[key]['nama']
  sks = datamatkul_10[key]['sks']
  hari = datamatkul_10[key]['hari']
  jam = datamatkul_10[key]['jam']
  print(f"{key:^5} {nama:^30} {sks:^3} {hari:^7} {jam:^13}")

print('\nSelamat belajar!!')

Berikut adalah jadwal kuliah anda selama semester genap

KODE               NAMA              SKS  HARI        JAM     
mat1   Algoritma dan Struktur Data    3   Senin  08.30 - 11.10
mat2         Struktur Aljabar         2   Senin  11.10 - 13.00
mat3           Kalkulus II            3  Selasa  08.30 - 11.10
mat4         Statistika Dasar         3  Selasa  11.10 - 13.50

Selamat belajar!!


In [17]:
# Latihan dictionaries 7
# Membuat program untuk merubah NIM yang berupa angka menjadi sebutan bilangan tersebut.

angka_10 = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan',
}

nama_10 = input('Nama : ')
nim_10 = input('NIM : ')
nim_angka_10 = " "
for data in nim_10 :
  nim_angka_10 += angka_10.get(data) + " "
print('NIM anda dalam sebutan bilangan antara lain :')
print(nim_angka_10)

Nama : NI GUSTI AYU AGUNG INDRASWARI
NIM : 2208541010
NIM anda dalam sebutan bilangan antara lain :
 dua dua nol delapan lima empat satu nol satu nol 


##**5.19 Fungsi dalam Python**
Tanpa disadari, dalam praktik-praktik sebelumnya telah menerapkan beberapa fungsi pada *Python* seperti fungsi *input*, *print, len, range*, dll.

Fungsi dibentuk untuk menghindari pengulangan yang tinggi dalam program yang kita buat. 

Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil.





In [18]:
# Latihan fungsi dalam python (1)

# Fungsi diawali dengan 'def'
def Halo_semuanya ():       # Fungsi didefinisikan
  print('Halo semuanya')
Halo_semuanya()             # Fungsi dipanggil

# Fungsi harus didefinisikan terlebih dahulu, baru dipanggil
# Jika dipanggil terlebih dahulu baru didefinisikan fungsi akan error

# Fungsi dengan argument (input)
# Argument dimasukkan di dalam tanda kurung biasa ( )
# Argument bisa berupa apapun baik string, angka, list, dll

print('\nDi bawah ini fungsi dengan input berupa string')
def tugas(matkul):                                                # Fungsi didefinisikan
  # Fungsi tugas menerima argument/input dengan variabel matkul
  print(f"Selamat mengerjakan tugas {matkul}")                    
tugas('algoritma dan struktur data')                              # Fungsi dipanggil

print('\nDi bawah ini fungsi dengan input berupa integer')
def sepatu(ukuran):
  print(f"Ukuran sepatu anda adalah {ukuran}")
sepatu(40)

Halo semuanya

Di bawah ini fungsi dengan input berupa string
Selamat mengerjakan tugas algoritma dan struktur data

Di bawah ini fungsi dengan input berupa integer
Ukuran sepatu anda adalah 40


##**5.19.1 Tugas Fungsi pada Python**
Ada dua jenis fungsi pada *Python* yaitu :

1. Menjalankan perintah.
2. Menampilkan hasil perhitungan



In [19]:
# Latihan tugas fungsi pada python (1)

# Fungsi dengan return
# return berfungsi untuk memanggil kembali variabel dari suatu fungsi

# Deklarasi fungsi bagi2
def bagi2 (angka):     # Disini saya membuat fungsi pembagian2 dengan input (10)
  hasil_10 = angka / 2      # Lalu, input (10) akan dibagi 2 menghasilkan 5.0
  return hasil_10           # Hasilnya dari operasi fungsinya akan dicetak kembali
a_10 = bagi2(10)
print(a_10)

b_10 = 10 + bagi2(7)
print(b_10)
# Disini saya mencoba dengan input yang berbeda
# Prosesnya tetep sama seperti sebelumnya
# Tapi, setelah input dibagi 2, hasilnya ditambahkan 10
# 7 / 2 = 3.5, kemudian 3.5 + 10 = 13.5
# Maka yang menjadi outputnya adalah 13.5 bukan 3.5

# Mencoba fungsi dengan banyak return
# Mendeklarasikan fungsi takukaba (tambah, kurang, kali, bagi)
# Pada fungsi dapat menginput lebih dari satu argumen/input
def takukaba (angka_1,angka_2):
  tambah = angka_1 + angka_2
  kurang = angka_1 - angka_2
  kali = angka_1 * angka_2
  bagi = angka_1 / angka_2
  return tambah, kurang, kali, bagi     # Gunakan tanda koma sebagai pemisah antar return

o,p,q,r = takukaba(15,4)
print(f"Hasil tambah = {o}")  # o sebagai variabel operasi tambah
print(f"Hasil kurang = {p}")  # p sebagai variabel operasi kurang
print(f"Hasil kali = {q}")    # q sebagai variabel operasi kali
print(f"Hasil bagi = {r}")    # r sebagai variabel operasi bagi
# Perintah print diatas menggunakan forrmatted string

5.0
13.5
Hasil tambah = 19
Hasil kurang = 11
Hasil kali = 60
Hasil bagi = 3.75


##**5.20 Numpy**
Numpy adalah salah satu *Library* dalam *Python* yang memiliki keunggulan dalam perhitungan bektor dan matriks dalam berbagai dimensi.

In [20]:
# Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut
import numpy as np

##**5.20.1 Perintah Dasar pada Numpy**


In [21]:
# Mendeklarasikan numpy
import numpy as np
# Mendeklarasikan variabel dengan fungsi array pada numpy
n_10 = np.array([2,3,4,5])
print('Ini adalah data array yang pertama : ', n_10)
a1 = n_10.ndim
b1 = n_10.shape
print('Dengan banyak baris ', a1, 'dan ordo', b1, '\n')

# Mendeklarasikan variabel baru berupa matriks
o_10 = np.array ([[3,4,5,6],
                  [7,8,9,10]])
print('Ini adalah data array yang kedua :', o_10 )

a2 = o_10.ndim
# fungsi 'ndim' berfungsi untuk menghitung banyaknya baris pada numpy
b2 = o_10.shape
# fungsi 'shape' berfungsi untuk menghitung ordo pada numpy
print('Dengan banyak baris ', a2, 'dan ordo', b2, '\n')


p_10 = np.array([
    [1,2,3,4],[2,3,4,5],
    [3,4,5,6],[4,5,6,7],
    [5,6,7,8],[6,7,8,9],
    [7,8,9,10],[8,9,10,11]
])
print('\nIni adalah daya array yang ketiga', p_10)
a3 = p_10.ndim
b3 = p_10.shape
print('Dengan banyak baris ', a3, 'dan ordo', b3, '\n')

Ini adalah data array yang pertama :  [2 3 4 5]
Dengan banyak baris  1 dan ordo (4,) 

Ini adalah data array yang kedua : [[ 3  4  5  6]
 [ 7  8  9 10]]
Dengan banyak baris  2 dan ordo (2, 4) 


Ini adalah daya array yang ketiga [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]
Dengan banyak baris  2 dan ordo (8, 4) 



##**5.20.2 Memanggil Anggota, Kolom, dan Baris dengan Numpy**

In [12]:
# Mendeklarasikan numpy
import numpy as np

# Mendeklarasikan variabel dengan fungsi array pada numpy
q_10 = np.array([
    [1,3,5,7],[2,4,6,8],[9,11,13,15]
])
print('Terdapat data array sebagai berikut :\n', q_10)

# Mendeklarasikan variabel dengan penjumlahan bertipe integer
r_10 = int(q_10[0,2]) + int(q_10[1,3])
print('\nHasil dari penjumlahan baris ke 0, kolom ke 2 dan baris ke 1, kolom ke 3 adalah ',r_10)

# Mendeklarasikan variabel untuk mencari index pertama pada seluruh data array
s_10 = q_10 [:,1]
print('\nBerikut urutan data pertama pada seluruh baris : ', s_10)

# Mendeklarasikan variabel untuk mencari seluruh index data array
t_10 = q_10[0,:]
print('\nBerikut urutan seluruh data dari baris ke 0 : ', t_10)

# Mendeklarasikan variabel untuk mencari index 1:3 pada data array ke 1
u_10 = q_10 [1,1:3]
print(u_10)

# Mendeklarasikan variabel untu mencari index 0:3:3 pada data array ke 2
v_10 = q_10[1, 0:3:3]
print(v_10)

# Mendeklarasikan variabel untuk mengganti index 2 pada data array ke 1
q_10[1,2] = 20
print(q_10)

Terdapat data array sebagai berikut :
 [[ 1  3  5  7]
 [ 2  4  6  8]
 [ 9 11 13 15]]

Hasil dari penjumlahan baris ke 0, kolom ke 2 dan baris ke 1, kolom ke 3 adalah  13

Berikut urutan data pertama pada seluruh baris :  [ 3  4 11]

Berikut urutan seluruh data dari baris ke 0 :  [1 3 5 7]
[4 6]
[2]
[[ 1  3  5  7]
 [ 2  4 20  8]
 [ 9 11 13 15]]


##**5.20.3 Matrix pada Numpy**

In [22]:
# Mendeklarasikan numpy
import numpy as np

# Mendeklarasikan variabel dengan fungsi 'ones(( ))' 
x1 = np.ones((3,4))
# 'ones(( ))' digunakan untuk membentuk entri '1.' pada seluruh entri array
# '(( ))' digunakan untuk ordo pada array 
print("Bentuk data array dengan ordo 3x4 yang memiliki seluruh entri '1.' : ",x1, '\n')

# Mendeklarasikan variabel dengan fungsi 'zeros(( ))'
x2 = np.zeros((4,3))
# 'zeros(( ))' digunakan untuk membentuk entri '0.' pada seluruh entri array
# '(( ))' digunakan untuk ordo pada array
print("Bentuk data array dengan ordo 4x3 yang memiliki seluruh entri '0.' : ",x2, '\n')

# Mendeklarasikan variabel dengan fungsi 'identity()'
x3 = np.identity(5)
# 'identity()' digunakan untuk membentuk matriks identitas
# dengan '()' digunakan sebagai ordo array
# karena matriks identitas adalah matrik bujursangkar, maka hanya perlu 1 ordo
print("Bentuk data array dengan ordo 5x5 yang merupakan matriks identitas yaitu : ",x3, '\n')

# Mendeklarasikan variabel dengan fungsi 'ones(( , , , ))'
x4 = np.ones((3,4,5))
# 'ones(( , , , ))' digunakan untuk membentuk entri '1.' pada seluruh entri array
# dengan '(( , , , ))' digunakan untuk membentuk berapa array, baris array, dan kolom array
print("Bentuk 3 data array dengan ordo 4x5 yang memiliki seluruh entri '1.' : ", x4, '\n')

# Mendeklarasikan variabel dengan fungsi 'full(( , ), )'
x5 = np.full((3,3),6)
# 'full(( , ), )' digunakan untuk membentuk data array dengan satu bentuk entri pada seluruh data
# dengan '(( , ), )' digunakan untuk membentuk ordo array dan data array yang ingin dibentuk
print("Bentuk data array dengan ordo 3x3 yang memiliki seluruh entri '6' : ", x5, '\n')

# Mendeklarasikan variabel dengan fungsi 'random.rand( , )'
x6 = np.random.rand(4,6)
# 'random.rand( , )' digunakan untuk membentuk data array yang berisi entri dengan nilai random
# dengan '( , )' digunakan untuk membentuk ordo array
print("Bentuk data array dengan ordo 4x6 yang memiliki seluruh entri random : ",x6, '\n')

# Mendeklarasikan variabel dengan fungsi 'random.randint( , ,size = ( , ))'
x7 = np.random.randint(1,10,size = (3,4))
# 'random.randint( , ,size = ( , ))' digunakan untuk membentuk data array yang berisi entri dengan nilai random
# namun, nilai random disini memiliki batas, dengan '( , ,size...)' sebagai batasnya
# dan 'size = ( , )' digunakan untuk membentuk ordo array
print("Bentuk data array dengan ordo 3x4 yang memiliki seluruh entri random dari 1-10 : ",x7, '\n')

Bentuk data array dengan ordo 3x4 yang memiliki seluruh entri '1.' :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Bentuk data array dengan ordo 4x3 yang memiliki seluruh entri '0.' :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Bentuk data array dengan ordo 5x5 yang merupakan matriks identitas yaitu :  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Bentuk 3 data array dengan ordo 4x5 yang memiliki seluruh entri '1.' :  [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

Bentuk data array dengan ordo 3x3 yang memiliki seluruh entri '6' :  [[6 6 6]
 [6 6 6]
 [6 6 6]] 

Bentuk data array dengan ordo 4x6 yang memiliki seluruh entri random :  [[0.43226222 0.86588329 0.56834412 0.85378624 0.27066454 0.80858499]
 [0.74299419 0.31904236 0.86426896 0.4028707

##**5.20.4 Copy pada Numpy**
Ikatan persamaan dalam *Numpy* begitu erat sehingga saat anggota variabel baru dirubah, dampaknya juga akan merubah variabel asal.

Untuk menghindari perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah *copy*



In [23]:
import numpy as np

# Mendeklarasikan variabel dengan fungsi array pada numpy
z_10 = np.array([1,3,5,7,9])
print("Diketahui data array(z_10) sebagai berikut : " ,z_10)
# variabel akan di 'copy' dengan fungsi 'copy()'
y_10 = z_10.copy()
# berikut adalh hasil copy variabel
print("Data tersebut akan dicopy pada array(y_10) seperti berikut : ",y_10)

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
w_10 = np.array([2,4,6,8])
print("\nDiketahui data array(w_10) sebagai berikut : ",w_10)
# variabel akan di 'copy' dengan fungsi 'copy()'
v_10 = w_10.copy()
# berikut adalah hasil copy variabel
print("Data tersebut akan dicopy pada array(v_10)  seperti berikut : ",v_10)

print("\nSehingga kedua array copy tersebut indentik dengan array originalnya : \n",y_10 ,v_10)

Diketahui data array(z_10) sebagai berikut :  [1 3 5 7 9]
Data tersebut akan dicopy pada array(y_10) seperti berikut :  [1 3 5 7 9]

Diketahui data array(w_10) sebagai berikut :  [2 4 6 8]
Data tersebut akan dicopy pada array(v_10)  seperti berikut :  [2 4 6 8]

Sehingga kedua array copy tersebut indentik dengan array originalnya : 
 [1 3 5 7 9] [2 4 6 8]


##**5.20.5 Operasi Matematika pada Numpy**

In [25]:
import numpy as np

# Mendeklarasikan variabel dengan fungsi array pada numpy
a_10 = np.array([7,8,9,10,11])
print("Diketahui data array sebagai berikut [7,8,9,10,11] \n")
b_10 = np.array([6,7,8,9,10])

# Mendeklarasikan variabel dengan operasi '+' pada variabel 'a_10'
# operasi '+' adalah operasi penjumlahan
y1 = a_10+1

# Mendeklarasikan variabel dengan operasi '-' pada variabel 'a_10'
# operasi '-' adalah operasi pengurangan
y2 = a_10-1

# Mendeklarasikan variabel dengan operasi '*' pada variabel 'a_10'
# operasi '*' adalah operasi perkalian
y3 = a_10*2

# Mendeklarasikan variabel dengan operasi '/' pada variabel 'a_10'
# operasi '/' adalah operasi pembagian
y4 = a_10/2

# Mendeklarasikan variabel dengan operasi '**' pada variabel 'a_10'
# operasi '**' adalah operasi pemangkatan
y5 = a_10**b_10
print("Nilai a_10 + 1 : " , y1,'\n')
print("Nilai a_10 - 1 : ", y2,'\n')
print("Nilai a_10 x 1 : ", y3,'\n')
print("Nilai a_10 / 1 : ", y4,'\n')
print("Nilai a_10 pangkat b_10 : ", y5,'\n')

# Mendeklarasikan variabel dengan operasi 'cos()'
z1 = np.cos(a_10)
# operasi 'cos()' adalah operasi pembentukan nilai cos dari data pada '()'

# berikut inisialisasi variabel dengan operasi 'sin()' 
z2 = np.sin(a_10)
# operasi 'sin()' adalah operasi pembentukan nilai sin dari data pada '()'

# Mendeklarasikan variabel dengan operasi 'tan()'
z3 = np.tan(a_10)
# operasi 'tan()' adalah operasi pembentukan nilai tan dari data pada '()'

# Mendeklarasikan variabel dengan operasi 'sinh()' 
z4 = np.sinh(a_10)
# operasi 'sinh()' adalah operasi pembentukan nilai sin hiperbolik dari data pada '()'

# Mendeklarasikan variabel dengan operasi 'cosh()' 
z5 = np.cosh(a_10)
# operasi 'cosh()' adalah operasi pembentukan nilai cos hiperbolik dari data pada '()'

# berikut inisialisasi variabel dengan operasi 'tanh()' pada variabel 'a'
# operasi 'tanh()' adalah operasi pembentukan nilai tan hiperbolik dari data pada '()'
z6 = np.tanh(a_10)

# Mendeklarasikan variabel dengan operasi 'sqrt()' 
# operasi 'sqrt()' adalah operasi yang mencari nilai akar kuadrat dari data '()'
z7 = np.sqrt(a_10)
print("Nilai cos adalah ", z1, '\n')
print("Nilai sin adalah ", z2, '\n')
print("Nilai tan adalah ", z3, '\n')
print("Nilai cosh adalah  ", z4, '\n')
print("Nilai sinh adalah  ",z5, '\n')
print("Nilai tanhadalah  ",z6, '\n')
print("Nilai akar kuadrat a adalah ",z7,'\n')

Diketahui data array sebagai berikut [7,8,9,10,11] 

Nilai a_10 + 1 :  [ 8  9 10 11 12] 

Nilai a_10 - 1 :  [ 6  7  8  9 10] 

Nilai a_10 x 1 :  [14 16 18 20 22] 

Nilai a_10 / 1 :  [3.5 4.  4.5 5.  5.5] 

Nilai a_10 pangkat b_10 :  [     117649     2097152    43046721  1000000000 25937424601] 

Nilai cos adalah  [ 0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257 ] 

Nilai sin adalah  [ 0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021] 

Nilai tan adalah  [   0.87144798   -6.79971146   -0.45231566    0.64836083 -225.95084645] 

Nilai cosh adalah   [  548.31612327  1490.47882579  4051.54190208 11013.2328747
 29937.07084925] 

Nilai sinh adalah   [  548.31703516  1490.47916125  4051.54202549 11013.2329201
 29937.07086595] 

Nilai tanhadalah   [0.99999834 0.99999977 0.99999997 1.         1.        ] 

Nilai akar kuadrat a adalah  [2.64575131 2.82842712 3.         3.16227766 3.31662479] 



##**5.20.6 Perkalian Matriks pada Numpy**
Perkalian matriks pada *Numpy* dapat menggunakan perintah *matmul*.

Perlu diperhatikan ukuran matriks yang akan dikalikan harus sesui dengan persyaratan. Misalnya matriks ukuran (2 x 3) dapat dilakukan perkalian dengan matriks ukuran (3 x 4)



In [26]:
import numpy as np

# Mendeklarasikan variabel dengan fungsi array pada numpy(np)
a = np.array([[6,7,8,9],[1,2,3,4]])
b = np.array([[10,11,12,13],[16,14,18,17]])
print("Diketahui data array : ")
print(a)
print(b)
      
# variabel sebelumnya akan dioperasikan dengan '*' pada sebuah variabel baru
# ini adalah bentuk perkalian masing-masing entri pada variabel fungsi array      
c = a*b
print("\nNilai dari a*b : ", c)      

# Mendeklarasikan variabel dengan fungsi array pada numpy(np)
e = np.array([[1,2], [3,4],[6,7],[10,11]])
      
print("\nDiketahui pula data array kedua : ")
print(e)

# variabel 'a' dan 'e' akan operasikan dengan fungsi 'matmul()' 
# fungsi 'matmul()' berfungsi untuk mengalikan kedua matriks
f = np.matmul(a,e)
print(f)
print("\nJika array 'a' dan 'e' diketahui sebagai matriks,")
print("Maka hasil kalinya adalah : ")
print(f)

Diketahui data array : 
[[6 7 8 9]
 [1 2 3 4]]
[[10 11 12 13]
 [16 14 18 17]]

Nilai dari a*b :  [[ 60  77  96 117]
 [ 16  28  54  68]]

Diketahui pula data array kedua : 
[[ 1  2]
 [ 3  4]
 [ 6  7]
 [10 11]]
[[165 195]
 [ 65  75]]

Jika array 'a' dan 'e' diketahui sebagai matriks,
Maka hasil kalinya adalah : 
[[165 195]
 [ 65  75]]


##**5.20.7 min, max, dan sum pada Numpy**


In [28]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
# dengan 3 baris dan 4 kolom
a = np.array([[1,3,5,7],
             [2,4,6,8],
             [9,11,13,15]])
print("Diketahui data array : ")
print(a)
print('\n')

# berikut adalah fungsi 'min()' pada data 'a'
# 'min()' digunakan untuk mencari nilai minimum data array
print("Nilai minimum dari data array adalah : ")
b = np.min(a)
print(b,'\n')

# berikut adalah fungsi 'min( , axis=0)' pada data 'a'
c = np.min(a,axis=0)
print("Data minimum baris data arrray adalah : " ,c,'\n')
# 'min( , axis=0)' digunakan untuk mencari data minimum pada baris data array
# dengan axis = 0 menujukan 'baris' data array

# berikut adalah fungsi 'min( , axis=1)' pada data 'a'

d = np.min(a,axis=1)
print("Data minimum kolom data array adalah : " ,d,'\n')
# 'min( , axis=1)' digunakan untuk mencari data minimum pada kolom data array
# dengan axis = 1 menujukan 'kolom' data array

# berikut adalah fungsi 'max()' pada data 'a'
e = np.max(a)
print("Nilai maksimum dari data array adalah : " ,e,'\n')
# 'max()' digunakan untuk mencari nilai maksimum data array

# berikut adalah fungsi 'max( , axis=0)' pada data 'a'
f = np.max(a,axis=0)
print("Data maksimum baris data array adalah : " ,f,'\n')
# 'max( , axis=0)' digunakan untuk mencari data maksimum pada baris data array
# dengan axis = 0 menujukan 'baris' data array

# berikut adalah fungsi 'max( , axis=1)' pada data 'a'
g = np.max(a,axis=1)
print("Data maksimum kolom data array adalah : " ,g,'\n')
# 'max( , axis=1)' digunakan untuk mencari data maksimum pada kolom data array
# dengan axis = 1 menujukan 'kolom' data array

# berikut adalah fungsi 'sum()' pada data 'a'
h1 = np.sum(a)
print("Jumlah data array adalah : " ,h1,'\n')
# 'sum()' digunakan untuk menjumlah seluruh data array

# berikut adalah fungsi 'sum( , axis=0)' pada data 'a'
h2 = np.sum(a,axis=1)
print("Jumlah data baris array adalah : " ,h2,'\n')
# 'sum( , axis=0)' digunakan untuk menjumlah data pada baris data array
# dengan axis = 0 menunjukan 'baris' data array

# berikut adalah fungsi 'sum( , axis=1)' pada data 'a'
h3 = np.sum(a,axis=1)
print("Jumlah data kolom array adalah : " ,h3,'\n')
# 'sum( , axis=1)' digunakan untuk menjumlah data pada kolom data array
# dengan axis = 1 menunjukan 'kolom' data array

Diketahui data array : 
[[ 1  3  5  7]
 [ 2  4  6  8]
 [ 9 11 13 15]]


Nilai minimum dari data array adalah : 
1 

Data minimum baris data arrray adalah :  [1 3 5 7] 

Data minimum kolom data array adalah :  [1 2 9] 

Nilai maksimum dari data array adalah :  15 

Data maksimum baris data array adalah :  [ 9 11 13 15] 

Data maksimum kolom data array adalah :  [ 7  8 15] 

Jumlah data array adalah :  84 

Jumlah data baris array adalah :  [16 20 48] 

Jumlah data kolom array adalah :  [16 20 48] 

